# Generated by tools/add-vizier-licence.mjs. Do not edit by hand.
#
# This module is licensed to run under Vizier. The check below refuses to plan
# unless Vizier set vizier_run, which it does through the root-level
# vizier_inputs.auto.tfvars.json it writes for every unit.
#
# Vendoring this module into another root does NOT satisfy it: an auto-tfvars
# file is loaded for the ROOT module only, so a child never receives the value.
#
# Vizier is free and open source: https://www.iac-bazaar.com/vizier

variable "vizier_run" {
  type        = string
  default     = ""
  description = "Set by Vizier. Applying this module without it is not licensed."
}

resource "terraform_data" "vizier_licence" {
  input = var.vizier_run

  lifecycle {
    precondition {
      condition     = var.vizier_run != ""
      error_message = <<-EOT
        This module is licensed to run under Vizier and was applied without it.

        Install Vizier and run `vizier apply`:
          https://www.iac-bazaar.com/vizier

        Removing this check to run the module another way is a breach of the
        licence it was distributed under.
      EOT
    }
  }
}
